"""
Process and combine monthly Airbnb listings datasets for Christchurch.

This script is responsible for the first stage of the Airbnb data-wrangling
pipeline.

Main steps:
    1. Find valid monthly Airbnb CSV files in listings_data/.
    2. Sort the monthly files chronologically.
    3. Check that no month is duplicated or missing.
    4. Check that the monthly source files have consistent columns.
    5. Load each monthly dataset.
    6. Filter each dataset to Christchurch City.
    7. Extract the month and year from the filename.
    8. Add year, month, and month_year columns.
    9. Concatenate all monthly Christchurch datasets.
   10. Produce summary statistics and missing-value counts.
   11. Save the combined dataset and summary.

Expected monthly input filenames:
    listings_Oct25.csv
    listings_Nov25.csv
    listings_Dec25.csv
    listings_Jan26.csv
    ...
    listings_June26.csv
    listings_July26.csv
    listings_Aug26.csv

The original Inside Airbnb download is named listings.csv. For this project,
each downloaded file is manually renamed to include its month and year before
being placed in listings_data/.

Only files following the project's monthly naming convention are treated as
raw monthly inputs. Files generated by later pipeline stages are ignored.

Outputs:
    listings_data/listings_christchurch_combined.csv
    listings_data/listings_christchurch_summary.csv

Run from the repository root:
    python process_listings.py
"""

import re
from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

DATA_DIR = Path("listings_data")

OUTPUT_FILE = DATA_DIR / "listings_christchurch_combined.csv"

SUMMARY_FILE = DATA_DIR / "listings_christchurch_summary.csv"

CHRISTCHURCH_FILTER_COL_CANDIDATES = [
    "region_parent_name",
    "neighbourhood_group",
    "region_name",
    "city",
    "neighbourhood_cleansed",
    "neighbourhood",
]

CHRISTCHURCH_FILTER_VALUE = "Christchurch City"

MONTH_MAP = {
    "jan": 1,
    "january": 1,
    "feb": 2,
    "february": 2,
    "mar": 3,
    "march": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "sep": 9,
    "sept": 9,
    "september": 9,
    "oct": 10,
    "october": 10,
    "nov": 11,
    "november": 11,
    "dec": 12,
    "december": 12,
}


# ---------------------------------------------------------------------------
# Filename handling
# ---------------------------------------------------------------------------

def parse_month_year_from_filename(filename: str) -> tuple[int, int, str]:
    """
    Extract the year, month, and display label from a monthly filename.

    Expected format:
        listings_<month><two-digit-year>.csv

    Examples:
        listings_Oct25.csv
            -> (2025, 10, "Oct-2025")

        listings_March26.csv
            -> (2026, 3, "March-2026")

        listings_July26.csv
            -> (2026, 7, "July-2026")

    Args:
        filename:
            Name of the monthly CSV file.

    Returns:
        A tuple containing:
            year, month number, month-year label.

    Raises:
        ValueError:
            If the filename does not follow the expected format or contains
            an unrecognised month.
    """
    match = re.fullmatch(
        r"listings_([A-Za-z]+)(\d{2})\.csv",
        filename,
        flags=re.IGNORECASE,
    )

    if not match:
        raise ValueError(
            f"Filename does not match the expected monthly format: {filename}"
        )

    month_text, year_text = match.groups()
    month_key = month_text.lower()

    if month_key not in MONTH_MAP:
        raise ValueError(
            f"Unrecognized month '{month_text}' in filename: {filename}"
        )

    month = MONTH_MAP[month_key]
    year = 2000 + int(year_text)

    month_year = f"{month_text.capitalize()}-{year}"

    return year, month, month_year


def find_monthly_files(data_dir: Path) -> list[Path]:
    """
    Find valid raw monthly Airbnb files and sort them chronologically.

    Generated pipeline outputs are ignored because they do not follow the
    monthly filename format.

    Args:
        data_dir:
            Directory containing the Airbnb CSV files.

    Returns:
        Valid monthly input files sorted by year and month.

    Raises:
        FileNotFoundError:
            If the data directory or monthly files cannot be found.
        ValueError:
            If more than one file represents the same month.
    """
    if not data_dir.exists():
        raise FileNotFoundError(
            f"Airbnb data directory not found: {data_dir}"
        )

    monthly_files = []

    for filepath in data_dir.glob("listings_*.csv"):
        try:
            year, month, _ = parse_month_year_from_filename(filepath.name)
        except ValueError:
            # Ignore generated files such as
            # listings_christchurch_cleaned.csv.
            continue

        monthly_files.append(
            (year, month, filepath)
        )

    if not monthly_files:
        raise FileNotFoundError(
            f"No valid monthly Airbnb files found in {data_dir}/. "
            "Expected filenames such as listings_Oct25.csv."
        )

    monthly_files.sort(
        key=lambda item: (item[0], item[1])
    )

    seen_periods = set()

    for year, month, filepath in monthly_files:
        period = (year, month)

        if period in seen_periods:
            raise ValueError(
                "Duplicate monthly Airbnb input detected for "
                f"{year}-{month:02d}. "
                f"Check the files in {data_dir}/."
            )

        seen_periods.add(period)

    return [
        filepath
        for _, _, filepath in monthly_files
    ]


# ---------------------------------------------------------------------------
# Input sanity checks
# ---------------------------------------------------------------------------

def check_month_continuity(files: list[Path]) -> None:
    """
    Check that no month is missing between the first and last input files.

    For example, if June and August are present but July is missing, the
    automated pipeline stops rather than silently creating an incomplete
    combined dataset.

    Args:
        files:
            Chronologically sorted monthly Airbnb files.

    Raises:
        ValueError:
            If one or more months are missing.
    """
    actual_periods = []

    for filepath in files:
        year, month, _ = parse_month_year_from_filename(
            filepath.name
        )

        actual_periods.append(
            pd.Period(
                year=year,
                month=month,
                freq="M",
            )
        )

    expected_periods = pd.period_range(
        start=actual_periods[0],
        end=actual_periods[-1],
        freq="M",
    )

    missing_periods = [
        period
        for period in expected_periods
        if period not in actual_periods
    ]

    if missing_periods:
        missing_labels = [
            period.strftime("%B %Y")
            for period in missing_periods
        ]

        raise ValueError(
            "Missing monthly Airbnb dataset(s): "
            + ", ".join(missing_labels)
        )


def check_source_schemas(files: list[Path]) -> None:
    """
    Check that all monthly source files contain the same set of columns.

    Comparing column names rather than only the number of columns helps
    detect changes in the source-data structure before concatenation.

    Args:
        files:
            Monthly Airbnb input files.

    Raises:
        ValueError:
            If a monthly file has different columns from the first file.
    """
    first_file = files[0]

    expected_columns = set(
        pd.read_csv(
            first_file,
            nrows=0,
        ).columns
    )

    for filepath in files[1:]:
        current_columns = set(
            pd.read_csv(
                filepath,
                nrows=0,
            ).columns
        )

        if current_columns != expected_columns:
            missing_columns = sorted(
                expected_columns - current_columns
            )

            extra_columns = sorted(
                current_columns - expected_columns
            )

            raise ValueError(
                f"Column structure differs in {filepath.name}.\n"
                f"Compared with: {first_file.name}\n"
                f"Missing columns: {missing_columns}\n"
                f"Extra columns: {extra_columns}\n"
                "Check that all monthly files use the same "
                "Inside Airbnb export format."
            )


# ---------------------------------------------------------------------------
# Christchurch filtering
# ---------------------------------------------------------------------------

def detect_filter_column(df: pd.DataFrame) -> str:
    """
    Find the most appropriate available column for filtering Christchurch.

    The candidate columns are checked in the order defined in the
    configuration section.

    Args:
        df:
            Airbnb DataFrame.

    Returns:
        Name of the selected geographic column.

    Raises:
        ValueError:
            If none of the expected geographic columns are present.
    """
    for column in CHRISTCHURCH_FILTER_COL_CANDIDATES:
        if column in df.columns:
            return column

    raise ValueError(
        "Could not find a geographic column for filtering Christchurch. "
        f"Expected one of: {CHRISTCHURCH_FILTER_COL_CANDIDATES}. "
        f"Available columns: {list(df.columns)}"
    )


def load_and_filter(
    filepath: Path,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Load one monthly Airbnb dataset and filter it to Christchurch City.

    The year and month are derived from the filename and added to the
    Christchurch-only data.

    Args:
        filepath:
            Path to one monthly Airbnb CSV.
        verbose:
            Whether processing information should be printed.

    Returns:
        Christchurch-only Airbnb rows with year, month, and month_year.

    Raises:
        ValueError:
            If the file is empty or no Christchurch rows are found.
    """
    df = pd.read_csv(
        filepath,
        low_memory=False,
    )

    if df.empty:
        raise ValueError(
            f"Monthly Airbnb file is empty: {filepath.name}"
        )

    raw_row_count = len(df)

    filter_column = detect_filter_column(df)

    if filter_column == "neighbourhood":
        mask = (
            df[filter_column]
            .astype(str)
            .str.contains(
                "Christchurch",
                case=False,
                na=False,
            )
        )

    else:
        mask = (
            df[filter_column]
            .astype(str)
            .str.strip()
            .str.lower()
            == CHRISTCHURCH_FILTER_VALUE.lower()
        )

    matched_row_count = int(
        mask.sum()
    )

    if verbose:
        print(
            f"  filter column: '{filter_column}' | "
            f"raw rows: {raw_row_count} | "
            f"Christchurch rows: {matched_row_count}"
        )

    if matched_row_count == 0:
        sample_values = (
            df[filter_column]
            .dropna()
            .unique()[:5]
        )

        raise ValueError(
            f"No Christchurch rows found in {filepath.name} "
            f"using '{filter_column}'. "
            f"Sample values: {list(sample_values)}"
        )

    filtered = df.loc[mask].copy()

    year, month, month_year = (
        parse_month_year_from_filename(
            filepath.name
        )
    )

    filtered["year"] = year
    filtered["month"] = month
    filtered["month_year"] = month_year

    return filtered


# ---------------------------------------------------------------------------
# Summary statistics
# ---------------------------------------------------------------------------

def build_summary(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create summary information for every column in the combined dataset.

    Numeric columns include:
        minimum, maximum, mean, standard deviation.

    Non-numeric columns include:
        number of unique values, most common value, and its frequency.

    All columns include:
        missing-value count and missing-value percentage.

    Args:
        df:
            Combined Christchurch Airbnb dataset.

    Returns:
        A DataFrame containing one summary row per input column.

    Raises:
        ValueError:
            If the combined dataset is empty.
    """
    if df.empty:
        raise ValueError(
            "Cannot create summary statistics for an empty dataset."
        )

    summary_rows = []

    for column in df.columns:
        series = df[column]
        missing_count = int(
            series.isna().sum()
        )

        missing_percentage = round(
            100 * missing_count / len(df),
            2,
        )

        if pd.api.types.is_numeric_dtype(series):
            summary_rows.append({
                "column": column,
                "dtype": "numeric",
                "min": series.min(),
                "max": series.max(),
                "mean": series.mean(),
                "std": series.std(),
                "n_unique_categories": None,
                "top_category": None,
                "top_category_count": None,
                "missing_count": missing_count,
                "missing_pct": missing_percentage,
            })

        else:
            value_counts = series.value_counts(
                dropna=True
            )

            if value_counts.empty:
                top_category = None
                top_category_count = None
            else:
                top_category = value_counts.index[0]
                top_category_count = int(
                    value_counts.iloc[0]
                )

            summary_rows.append({
                "column": column,
                "dtype": "categorical",
                "min": None,
                "max": None,
                "mean": None,
                "std": None,
                "n_unique_categories": int(
                    series.nunique(
                        dropna=True
                    )
                ),
                "top_category": top_category,
                "top_category_count": top_category_count,
                "missing_count": missing_count,
                "missing_pct": missing_percentage,
            })



    return pd.DataFrame(
        summary_rows
    )


# ---------------------------------------------------------------------------
# Main processing stage
# ---------------------------------------------------------------------------

def main() -> None:
    """
    Run the monthly Airbnb preprocessing stage.

    The function discovers and validates the monthly inputs, processes every
    month using the same reusable function, combines the Christchurch data,
    produces summary statistics, and writes the outputs.

    Errors are allowed to stop the script so that a later orchestration file
    can detect that this pipeline stage failed.
    """
    files = find_monthly_files(
        DATA_DIR
    )

    check_month_continuity(
        files
    )

    check_source_schemas(
        files
    )

    print(
        f"Found {len(files)} valid monthly Airbnb files:"
    )

    for filepath in files:
        _, _, month_year = (
            parse_month_year_from_filename(
                filepath.name
            )
        )

        print(
            f"  - {filepath.name} ({month_year})"
        )

    print(
        "\nInput sanity checks passed."
    )

    monthly_frames = []

    for filepath in files:
        monthly_df = load_and_filter(
            filepath
        )

        monthly_frames.append(
            monthly_df
        )

        print(
            f"Processed {filepath.name}: "
            f"{len(monthly_df)} Christchurch rows"
        )

    combined = pd.concat(
        monthly_frames,
        ignore_index=True,
    )

    if combined.empty:
        raise ValueError(
            "Combined Airbnb dataset is empty after preprocessing."
        )

    period_summary = (
        combined[
            ["year", "month", "month_year"]
        ]
        .drop_duplicates()
        .sort_values(
            ["year", "month"]
        )
    )

    first_period = (
        period_summary.iloc[0]["month_year"]
    )

    last_period = (
        period_summary.iloc[-1]["month_year"]
    )

    print(
        f"\nCombined dataset: "
        f"{len(combined)} rows, "
        f"{len(combined.columns)} columns"
    )

    print(
        f"Dataset period: "
        f"{first_period} to {last_period}"
    )

    print("\nMonths included:")

    for month_year in period_summary["month_year"]:
        print(
            f"  - {month_year}"
        )

    summary = build_summary(
        combined
    )

    # The input directory already exists if the earlier checks passed, but
    # mkdir keeps output writing safe if the output location is changed later.
    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    combined.to_csv(
        OUTPUT_FILE,
        index=False,
    )

    summary.to_csv(
        SUMMARY_FILE,
        index=False,
    )

    # Confirm that the expected outputs were actually created.
    if not OUTPUT_FILE.exists():
        raise RuntimeError(
            f"Combined output was not created: {OUTPUT_FILE}"
        )

    if not SUMMARY_FILE.exists():
        raise RuntimeError(
            f"Summary output was not created: {SUMMARY_FILE}"
        )

    print(
        f"\nCombined dataset saved to: "
        f"{OUTPUT_FILE}"
    )

    print(
        f"Summary statistics saved to: "
        f"{SUMMARY_FILE}"
    )

    print(
        f"\nAirbnb preprocessing completed successfully. "
        f"{len(files)} monthly files were processed "
        f"from {first_period} to {last_period}."
    )


if __name__ == "__main__":
    main()